version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Installing npm dependencies
          command: npm install
      - run:
          name: Resetting package-lock changes
          command: git checkout -- package-lock.json
      - run:
          name: Preparing lockfile update
          command: $(npm bin)/greenkeeper-lockfile-update
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      # Test
      - run:
          name: Linting source files
          command: npm run lint -- --format junit --output-file ~/reports/eslint.xml
          when: always

      # Store Results
      - store_test_results:
          path: ~/reports
          when: always
      - store_artifacts:
          path: ~/reports
          when: always

      # Deployment
      - add_ssh_keys
      - deploy:
          name: Updating lockfile
          command: $(npm bin)/greenkeeper-lockfile-upload
          environment:
            GH_TOKEN: $RELEASE_GITHUB_TOKEN
      - deploy:
          name: Deploy changes
          command: |
            echo "Setting up git user"
            git config --global user.email circleci@circleci && git config --global user.name CircleCI

            echo "Logging in to npm"
            echo "$NPM_TOKEN" > ~/.npmrc

            npx bump-version release --release-files out docs/api --gh-token $RELEASE_GITHUB_TOKEN
